# -*- coding: utf-8 -*-
r"""功能体检：把 AGENTS.md 里列过的能力逐条当断言，检查 frontend/app.js 是否都还在。

背景：2026-09-22 整体重写 app.js 时丢了「消息重排」等细节，
      这类回归 jsbalance（只看括号）和 check_ids（只看 DOM id）都抓不到。
      以后大改前端后跑一次这个，能立刻看出少了什么。

用法：python tools\check_features.py
"""

from __future__ import annotations

import io
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# (分组, 说明, 正则) —— 正则必须能在 app.js 里命中
CHECKS = [
    # ---- 后端接口（少一个就意味着某块功能没接上）----
    ("接口", "会话列表", r"/api/session\?limit=\d+&order=desc"),
    ("接口", "历史消息", r"/message\?limit=\d+"),
    ("接口", "发消息", r"/prompt`"),
    ("接口", "中断生成", r"/interrupt`"),
    ("接口", "新建会话", r'api\("/api/session",\s*\{\s*method:\s*"POST"'),
    ("接口", "删除会话", r'method:\s*"DELETE"'),
    ("接口", "会话改名", r'method:\s*"PATCH"'),
    ("接口", "实时事件 SSE", r'new EventSource\("/api/event"\)'),
    ("接口", "权限查询/回复", r"/permission`"),
    ("接口", "健康检查", r'api\("/healthz"\)'),
    ("接口", "心跳", r'fetch\("/heartbeat"'),
    ("接口", "关窗信号", r'"/bye"'),
    ("接口", "原生选文件夹 /pick/folder", r'"/pick/folder"'),
    ("接口", "cocraft 后端/WS 地址接口 /cocraft/_url", r'"/cocraft/_url"'),
    # ---- QQ音乐 ----
    ("音乐", "状态轮询", r'api\("/qq/state"\)'),
    ("音乐", "播放控制", r'api\("/qq/control"'),
    ("音乐", "音量", r'api\("/qq/volume"'),
    ("音乐", "歌词", r"/qq/lyrics\?title="),
    ("音乐", "条内搜索=弹窗搜索", r'musicSearch\(\$\("p-q"\)\.value\)'),
    ("音乐", "词按钮联动歌词", r'\$\("p-lyric-btn"\)\.addEventListener'),
    ("音乐", "进度条可拖动", r'\$\("p-seek"\)'),
    ("音乐", "刷新后恢复歌曲状态", r"function restoreMusicState"),
    ("音乐", "状态落盘 localStorage", r"localStorage\.setItem\(MUS_KEY"),
    ("音乐", "自动连播 / 随机下一首", r"async function musicNext"),
    ("音乐", "随机播放开关", r'\$\("p-shuffle"\)'),
    ("音乐", "自动连播开关", r'\$\("p-loop"\)'),
    ("音乐", "已移除启动QQ客户端按钮", r"NOT:p-app"),
    ("音乐", "真频谱", r'api\("/qq/spectrum"\)'),
    ("音乐", "真频谱开关 class", r'classList\.toggle\("real"'),
    ("音乐", "纯听歌模式同步", r"syncLyricsVisibility"),
    ("音乐", "歌词只显示三行", r'line\(idx - 1, "prev"\)|class="prev"'),
    ("音乐", "★歌词气泡球（收起时开关）", r'\$\("lyric-ball"\)'),
    ("音乐", "气泡球空闲贴边缩成小箭头", r"LB\.idle"),
    ("音乐", "气泡球可拖动定位（跟手）", r'addEventListener\("pointerdown"'),
    ("音乐", "展开时歌词横向滚动", r"lyrMarquee|updatePlayerLyric"),
    ("音乐", "歌词开关意愿落盘", r"LYR_PREF_KEY|cocraft\.lyrics\.wanted"),
    ("音乐", "★音乐条背景可换", r"applyChromeAppearance|playerbg"),
    ("安装包", "★Key 变量名按当前 agent 决定（不被别的 Key 顶掉）", r"varEl\.textContent = guessKeyName\(\)"),
    ("安装包", "★扫描本机 agent 弹窗", r'action: "scan"'),
    ("安装包", "★面板窗口可切原生/浏览器", r'api\("/panel/window"'),
    ("安装包", "可用的一键加入", r"addAllCandidates"),
    ("消息", "★空助手消息给友好提示（不糊 JSON）", r"这一轮确实没有返回正文"),
    ("消息", "★接续入口（措辞不再是导入）", r"接续中…"),
    ("消息", "接续后按 attach 给不同提示", r"historyImported"),
    ("消息", "列表显示对面历史条数", r"条历史"),
    ("消息", "★每条回答都有「复制」按钮", r'class="copy-btn" data-copy='),
    ("消息", "★代码块也有「复制」", r'class="copy-code"'),
    ("消息", "★复制走剪贴板（异步 API + execCommand 兜底）", r"async function copyToClipboard"),
    ("消息", "★复制正文从权威数据取（实时缓冲优先，不靠 DOM）", r"function copyMessageById"),
    ("消息", "★复制后按钮给瞬时反馈", r"function flashCopied"),
    # ---- 消息渲染（重写过的高危区）----
    ("消息", "★按时间升序重排", r"\.sort\(\(a,\s*b\)\s*=>"),
    ("消息", "用户消息读顶层 text", r"typeof m\.text === \"string\""),
    ("消息", "助手消息读 content 数组", r"Array\.isArray\(m\.content\)"),
    ("消息", "工具调用渲染", r"function renderToolPart"),
    ("消息", "思考过程渲染", r"function renderReasoningPart"),
    ("消息", "★思考块默认展开（details 需要 open，不只是 class）", r'class="part auto-open" open'),
    ("消息", "附件渲染", r"function renderAttachments"),
    ("消息", "未知结构兜底展示", r"原始数据"),
    ("消息", "内容指纹（避免重建整块）", r"function signatureOf"),
    ("消息", "重渲染时保住展开状态", r"details\[data-k\]"),
    ("消息", "空会话首屏卡片", r"function heroHtml\("),
    ("外观", "★首屏主图/贴纸/文案可自定义（SET.heroL1）", r"heroL1"),
    ("外观", "自定义素材走 /appearance/img 代理", r"/appearance/img\?k="),
    ("外观", "选图走原生对话框 /pick/image", r'api\("/pick/image"'),
    ("外观", "★素材清单接口 /appearance", r'api\("/appearance"\)'),
    ("外观", "换图后重画首屏与消息区", r"function refreshAppearanceArt"),
    ("消息", "Markdown 块级渲染(表格/列表/引用)", r"function renderBlocks"),
    ("消息", "Markdown 行内渲染(链接/加粗/斜体)", r"function inlineMd"),
    ("消息", "GFM 表格识别", r"MD_SEP"),
    # ---- 实时增量 ----
    ("实时", "文本增量", r"session\.text\.delta"),
    ("实时", "★本轮出错给提示（session.error）", r'session\.error'),
    ("实时", "思考增量", r"session\.reasoning\.delta"),
    ("实时", "步骤开始(agent/model)", r"session\.step\.started"),
    ("实时", "工具调用事件", r"session\.tool\.called"),
    ("实时", "终态白名单", r"const TERMINAL ="),
    ("实时", "打字机循环", r"requestAnimationFrame"),
    ("实时", "本地乐观回显", r"state\.pending\.push"),
    # ---- 交互 ----
    ("交互", "发送（Enter）", r'key === "Enter" && !e\.shiftKey'),
    ("交互", "Esc 中断/清附件", r'key === "Escape"'),
    ("交互", "Ctrl+B 收起侧栏", r'e\.key === "b"'),
    ("交互", "跟随滚动策略", r'state\.follow = false'),
    ("交互", "输入框自动长高", r"scrollHeight"),
    ("交互", "粘贴图片", r'"paste"'),
    ("交互", "拖拽文件", r'"drop"'),
    ("交互", "附件压缩", r"function shrinkImage"),
    ("交互", "左上角名字可编辑", r"plaintext-only"),
    ("交互", "主题记忆", r"localStorage\.setItem\(THEME_KEY"),
    ("交互", "侧栏状态记忆", r"localStorage\.setItem\(SIDEBAR_KEY"),
    ("交互", "落樱+涟漪", r"petal-unit"),
    ("交互", "会话删除按钮", r'class="del" data-del='),
    ("交互", "删除前二次确认", r'confirm\(`删除会话'),
    ("交互", "删除当前会话后清空界面", r"async function deleteSession"),
    ("交互", "首问自动命名", r"async function autoNameSession"),
    ("交互", "已命名的会话不覆盖", r"function shouldAutoName"),
    ("交互", "标题截断+压平空白", r"function titleFromQuestion"),
    # ---- 弹窗（agent 会被静默卡住的那两类）----
    ("弹窗", "表单轮询", r"api\(`/api/session/\$\{sid\}/form`"),
    ("弹窗", "权限轮询", r"/permission`"),
    ("弹窗", "表单提交", r"/form/\$\{encodeURIComponent\(form\.id\)\}/reply"),
    ("弹窗", "权限回复", r"/permission/\$\{encodeURIComponent\(perm\.id\)\}/reply"),
    ("弹窗", "选项记账(防轮询清空)", r"ASK\.picks\[key\] ="),
    ("弹窗", "同项不重建 DOM", r"if \(sig === ASK\.sig"),
    ("弹窗", "必填校验", r"还差："),
    # ---- 动态壁纸（Wallpaper Engine 原片）----
    ("壁纸", "创意工坊壁纸清单", r'api\("/live/wallpapers"\)'),
    ("壁纸", "有原片才切 has-live", r'classList\.add\("has-live"\)'),
    ("壁纸", "主题/侧栏变化自动同步", r"new MutationObserver\(sync\)"),
    ("壁纸", "加载失败退回 CSS 动态层", r'addEventListener\("error"'),
    ("壁纸", "清单定期重拉(新订阅免刷新)", r"5 \* 60 \* 1000"),
    ("壁纸", "播放速度可调", r"let liveRate = "),
    ("壁纸", "倍速赋值有越界保护", r"const setRate = \(r\)"),
    # ---- 设置面板 ----
    ("设置", "顶栏设置按钮", r'\$\("btn-cfg"\)'),
    ("设置", "背景亮度按主题可调", r'--bg-dim-hiru'),
    ("设置", "背景毛玻璃可调", r'--bg-blur'),
    ("设置", "设置落盘", r'localStorage\.setItem\(SET_KEY'),
    ("设置", "动态壁纸开关", r"!SET\.live"),
    ("设置", "任务栏开关", r'\$\("cfg-taskbar"\)'),
    ("设置", "任务栏开关默认开启", r"taskbar: true"),
    ("设置", "任务栏开关同步给守护", r'fetch\("/panel/taskbar"'),
    ("设置", "两侧音频条开关", r'\$\("cfg-spec-sides"\)'),
    ("设置", "两侧音频条默认开启", r"spectrumSides: true"),
    ("设置", "两侧音频条绘制", r"function paintSides"),
    ("设置", "两侧音频条高度可调", r'\$\("cfg-spec-h"\)'),
    ("设置", "两侧音频条高度默认值", r"spectrumSidesH: 100"),
    ("设置", "两侧音频条高度写进 CSS 变量", r'"--spec-side-h"'),
    ("设置", "两侧音频条起伏可调", r'\$\("cfg-spec-gain"\)'),
    ("设置", "两侧音频条起伏默认值", r"spectrumSidesGain: 120"),
    ("设置", "两侧音频条起伏写进 CSS 变量", r'"--spec-side-gain"'),
    ("设置", "两侧音频条起伏按倍数绘制", r"\* gain"),
    ("设置", "左上角名字设置", r'\$\("cfg-brand"\)'),
    ("设置", "左上角小标签设置", r'\$\("cfg-brand-sub"\)'),
    ("设置", "名字默认值", r'BRAND_DEFAULT = "絵梨衣"'),
    ("设置", "小标签默认值", r"BRAND_SUB_DEFAULT"),
    ("设置", "会话详情展开", r"function sessionDetailHtml"),
    ("设置", "会话详情状态记账", r"detailOpen"),
    ("设置", "会话详情按钮", r'class="info"'),
    ("设置", "★会话项显示所属项目（右下角）", r'class="proj"'),
    ("设置", "项目名取工作目录末段", r"function projectNameOf"),
    ("设置", "顶栏不再显示会话 ID", r'NOT:\$\("session-meta"\)\.textContent = state\.current\.id'),
    ("设置", "恢复默认", r"Object\.assign\(SET, SET_DEFAULT\)"),
    ("壁纸", "换片先藏视频防黑屏", r'classList\.remove\("ready"\)'),
    ("壁纸", "出第一帧才显示", r'classList\.add\("ready"\)'),
    ("壁纸", "展开＝暂停视频当背景", r"ensureVisibleFrame\(t\)"),
    ("壁纸", "片头黑场只量亮度(不截图)", r"const frameMean = "),
    ("壁纸", "已删掉冻结帧层", r"NOT:has-freeze"),
    ("壁纸", "已不再抓帧", r"NOT:function grabFrame"),
    ("壁纸", "已不再把画面转成图片", r"NOT:toDataURL"),
    ("壁纸", "壁纸列表接口", r'api\("/live/list"\)'),
    ("壁纸", "选择落盘保存", r'api\("/live/pick"'),
    ("壁纸", "已移除分类筛选按钮", r"NOT:wp-fb"),
    ("壁纸", "壁纸搜索框", r'\$\("wp-q"\)'),
    ("壁纸", "设置里选壁纸", r'\$\("cfg-wall"\)'),
    ("壁纸", "动态壁纸目录可改", r'\$\("cfg-wall-root"\)'),
    ("壁纸", "读取动态壁纸目录", r"async function loadWallpaperRoot"),
    ("壁纸", "保存动态壁纸目录", r"async function saveWallpaperRoot"),
    ("壁纸", "点按钮选择文件夹", r"async function pickWallpaperRoot"),
    ("壁纸", "目录接口 /live/root", r'api\("/live/root"'),
    ("壁纸", "目录选择接口 /live/root/pick", r'api\("/live/root/pick"'),
    ("壁纸", "已移除按 kind 过滤", r"NOT:WALL\.kind"),
    ("壁纸", "已移除 scene 静帧分支", r"NOT:urls\.still"),
    ("壁纸", "已移除 scene 解包标注", r"NOT:解包·"),
    ("壁纸", "已移除 /live/we 调用", r"NOT:/live/we"),
    ("壁纸", "已移除壁纸自带音乐开关", r"NOT:btn-wemusic"),
    ("壁纸", "已移除 weMusic 设置", r"NOT:weMusic"),
    ("壁纸", "已移除 we-shot 图层", r"NOT:we-shot"),
    ("壁纸", "选壁纸后立刻换片", r"if \(liveReload\) await liveReload\(\)"),
    ("壁纸", "收起时缓慢启动", r"ramp\(liveRate, LIVE_RAMP_IN\)"),
    ("壁纸", "展开时缓慢停止", r"ramp\(LIVE_START_RATE, LIVE_RAMP_OUT\)"),
    ("壁纸", "出帧后也会确认不是黑场", r'addEventListener\("loadeddata"'),
    # ---- 音乐（面板内搜歌/放歌 · 网易云非官方接口）----
    ("音乐", "折叠箭头常驻", r'\$\("p-fold"\)'),
    ("音乐", "搜索接口", r"/music/search\?p="),
    ("音乐", "播放流代理", r"/music/stream\?p="),
    ("音乐", "登录态查询", r'api\("/music/status"\)'),
    ("音乐", "贴 Cookie 登录", r'api\("/music/cookie"'),
    ("音乐", "条内结果渲染", r"function renderBarResults"),
    ("音乐", "平台切换(网易云/QQ)", r"\.wp-pb"),
    ("音乐", "已移除音乐条歌单按钮", r"NOT:p-lib"),
    ("音乐", "歌词位置按采样时间补时", r"MUSIC\.posAt = Number\(\(MUSIC\.state \|\| \{\}\)\.ts\)"),
    ("音乐", "推荐歌单封面", r"/music/cover\?p="),
    ("音乐", "选完歌单清封面缓存", r'api\("/music/cover/clear"'),
    ("音乐", "歌曲行封面(条内)", r'coverHtml\(it, "it-cover"\)'),
    ("音乐", "歌曲行封面(主页)", r'coverHtml\(it, "s-cover"\)'),
    # ---- 模型切换（顶栏「模型」按钮）----
    ("模型", "顶栏模型按钮", r'\$\("btn-model"\)'),
    ("模型", "模型清单接口", r'api\("/api/model"\)'),
    ("模型", "默认模型接口", r'api\("/api/model/default"\)'),
    ("模型", "切换写入当前会话", r'/model`,'),
    ("模型", "变体(variant)可点", r"ref\.variant = b\.dataset\.var"),
    ("模型", "新会话默认模型落盘", r"localStorage\.setItem\(MODEL_KEY"),
    ("模型", "新建会话带上模型", r"\.model = def"),
    ("模型", "按 provider 分组", r"mdl-group"),
    ("模型", "免费/付费标注", r"免费"),
    ("模型", "当前模型高亮", r"mdl-it\$\{on"),
    ("模型", "搜索过滤", r"\.toLowerCase\(\)\.includes\(q\)"),
    ("模型", "按钮跟随当前会话", r"updateModelBtn\(\)"),
    ("模型", "官方图标映射表", r"const MODEL_ICONS ="),
    ("模型", "图标解析顺序", r"function iconKeyFor"),
    ("模型", "本地图标目录", r'MODEL_ICON_DIR = "/assets/models/"'),
    ("模型", "顶栏用图标代替名字", r"b\.innerHTML = modelIconHtml"),
    ("模型", "无品牌标用字母徽章", r"micon-mono"),
    ("模型", "默认模型文案中性化", r"跟随引擎默认"),
    ("模型", "未知费用不谎报免费", r"费用未知"),
    ("模型", "★模型下架时自动修复（不再静默不回答）", r"async function repairStaleModel"),
    ("模型", "模型可用性判断（清单为空不误杀）", r"function modelAvailable"),
    ("模型", "★打开会话就体检模型", r"repairStaleModel\(state\.current\)"),
    ("模型", "发送前也校验已绑模型", r"modelAvailable\(cur\)"),
    ("设置", "首次设置向导", r"async function openSetup"),
    ("设置", "首次设置记账键", r'cocraft\.setup\.v1'),
    ("设置", "★新会话可选工作目录（弹窗）", r"function openNewSession"),
    ("设置", "★群聊：右边触发带开合抽屉", r"function initCocraft"),
    ("设置", "群聊记住开合", r"cocraft\.open"),
    ("设置", "★群聊 REST 走 /cocraft 代理", r'fetch\("/cocraft"'),
    ("设置", "★群聊发消息/实时走 WebSocket", r"new WebSocket\("),
    ("设置", "★群聊：会话列表 + 聊天内容", r"function ccRenderChats"),
    ("设置", "★群聊：聊天记录渲染", r"function ccRenderMsgs"),
    ("设置", "★群聊：抽屉宽度可拖动", r"function ccInitResize"),
    ("设置", "群聊 token 落盘", r"cocraft\.token"),
    ("设置", "★群聊会话菜单开合", r"function ccMenuOpen"),
    ("设置", "★群聊邀请成员", r"async function ccInvite"),
    ("设置", "★群聊移出成员", r"async function ccRemoveMember"),
    ("设置", "群聊成员变动后刷新成员行", r"async function ccRefreshChat"),
    ("设置", "★群聊刷新有反馈（未登录先校验）", r"async function ccRefreshAll"),
    ("设置", "★群聊：用户信息接口 GET /users/{id}", r'"/users/" \+ encodeURIComponent'),
    ("设置", "★群聊：用户缓存（登录/注册预填）", r"function ccCacheUser"),
    ("设置", "★群聊：显示名走缓存/接口（兜底）", r"function ccUserName"),
    ("设置", "★群聊：消息发送者显示用户名", r"ccUserName\(m\.sender_id\)"),
    ("设置", "★群聊：用户缓存落盘", r"CC_USERS_KEY"),
    # ---- 群聊文件传输 ----
    ("设置", "★上传文件 multipart /chats/{id}/files", r"/chats/\$\{encodeURIComponent\(CC\.chatID\)\}/files"),
    ("设置", "★文件消息渲染（message_type=file）", r'message_type === "file"'),
    ("设置", "★文件下载 URL 带 token", r"function ccFileUrl"),
    ("设置", "★上传只带鉴权、不带 Content-Type（保留 multipart 边界）", r'headers: \{ Authorization: "Bearer " \+ CC\.token \}'),
    ("设置", "★图片文件内联预览", r"cc-img"),
    ("设置", "★群聊图片点开放大预览（面板内复用 #img-view）", r'e\.target\.closest\("\[data-cc-img\]"\)'),
    ("设置", "★放大预览用 data-cc-img 承载 URL", r"data-cc-img"),
    ("设置", "顶栏刷新也有反馈", r"已重新加载消息"),
    ("设置", "★不再自动刷新（防 WebView2 卡死）", r"NOT:ui-reloaded"),
    ("设置", "有新版本只提示手动刷新", r"let updateReady"),
    ("设置", "★群聊分屏：给 html 加 cc-open", r'classList\.toggle\("cc-open"'),
    ("设置", "★群聊宽度写进 :root（分屏靠它）", r'documentElement\.style\.setProperty\("--cc-w"'),
    ("设置", "★群聊不自动打开（防卡死）", r"NOT:if \(wasOpen\) setCocraft"),
    ("设置", "新会话选目录走原生框 /pick/folder", r'api\("/pick/folder"'),
    ("设置", "记住上次工作目录", r"cocraft\.newsession\.dir"),
    ("设置", "首次设置应用引擎/agent", r"async function setupNext"),
    # ---- 微信（截图+OCR 只读识别；回复必须二次确认）----
    # ---- 龙族视觉 + 歌词翻译 ----
    ("龙族", "歌词翻译开关", r'\$\("cfg-zh"\)'),
    ("龙族", "翻译开关默认开启", r"zh: true"),
    ("龙族", "按开关决定是否翻译", r"&tr=\$\{SET\.zh \? 1 : 0\}"),
    ("龙族", "译文渲染成小字行", r'<span class="zh">'),
    ("龙族", "关翻译时隐藏译文", r"no-lyrics-zh"),
    # ---- 对话引擎（后端 /engine；S4）----
    ("引擎", "引擎状态接口", r'api\("/engine/status"\)'),
    ("引擎", "引擎切换接口", r'api\("/engine",\s*\{\s*method:\s*"POST"'),
    ("引擎", "切换后重连 SSE(防旧引擎事件)", r'if \(typeof connectEvents === "function"\) connectEvents\(\);'),
    ("引擎", "无引擎时优雅禁用下拉", r'sel\.disabled = true'),
    # ---- 默认 agent / 模型中性化（provider 有入口、引擎能看出可用性）----
    ("中性化", "★引擎下拉标出「未就绪」", r"（未就绪）"),
    ("中性化", "不可用引擎禁选", r'value="\$\{esc\(id\)\}"\$\{ok \? "" : " disabled"\}'),
    ("中性化", "记住引擎自述（label/available）", r"ENGINE\.engines"),
    ("中性化", "向导自动落到可用引擎并说明", r"已先帮你选到可用的"),
    ("中性化", "卡片显示 provider 徽章", r'class="badge">\$\{esc\(prov\)\}'),
    ("中性化", "provider 推断提示（≈）", r"≈\$\{esc\(guess\)\}"),
    ("中性化", "★agent 编辑弹窗（含 provider）", r"function editAgentCommand"),
    ("中性化", "provider 一键自动推断", r"async function guessAgentProvider"),
    ("中性化", "保存 agent 编辑（名称/命令/目录/provider）", r"async function saveAgentEdit"),
    ("中性化", "命令解析（引号包住含空格路径）", r"function parseCmd"),
    ("中性化", "ACP 说明文案中立", r"选择要驱动的 ACP agent"),
    ("中性化", "★模型 id 的 provider 前缀也用来找图标", r'id\.split\("/"\)\[0\]'),
    ("中性化", "已删除点名 Codex/dsh 的旧文案", r"NOT:Codex / dsh / …"),
    ("可选组件", "★前端显示「音乐服务未安装」", r"async function musicComponent"),
    ("可选组件", "未装时搜索直接拦下（不撞 502）", r"MUS\.installed === false"),
    ("API Key", "★设置里能填/清模型 Key", r"async function saveApiKey"),
    ("API Key", "按 provider 猜变量名", r"KEY_NAME_BY_PROVIDER"),
    ("API Key", "打开设置就拉（只拿掩码）", r'loadApiKeyRow\("cfg"\)'),
    # ---- 智能体 / 模式切换 ----
    ("模式", "★模式清单接口 /api/agent", r'api\("/api/agent"\)'),
    ("模式", "★切换模式：POST /api/session/{id}/agent", r"/agent`,\s*\{\s*method:\s*\"POST\""),
    ("模式", "★过滤内部 agent（hidden）", r"!a\.hidden"),
    ("模式", "新会话默认模式落盘", r"MODE_KEY"),
    ("模式", "新建会话后补一次应用", r"async function ensureSessionMode"),
    ("模式", "顶栏按钮文案跟随会话", r"function renderModeButton"),
    ("模式", "★切模式后默认跟随最后一次选择", r"以后新会话也用这个"),
    ("会话", "★切引擎后自动接续同一条会话", r"已接续当前会话"),
    ("会话", "★对面没有就在 ACP 侧「接续」进来", r"已把上一条会话接续进来"),
    ("模式", "跟随引擎默认（清本地默认）", r"mode-default"),
    # ---- 在外部程序里打开目录 ----
    ("打开", "★顶栏「工具」菜单（扳手）", r'\$\("tools-menu"\)'),
    ("打开", "★外部打开接口 /open/dir", r'"/open/dir"'),
    ("打开", "★当前会话目录", r"function currentDir"),
    # ---- 面板内终端（ConPTY）----
    ("终端", "★终端开关（工具菜单里）", r"function termToggle"),
    ("终端", "★收起抽屉不销毁终端（下次秒开）", r"const reuse = "),
    ("终端", "★页面卸载才删终端会话", r'fetch\("/pty/" \+ TERM\.id'),
    ("终端", "★点终端任意处聚焦输入区", r'termBox\.addEventListener\("pointerdown"'),
    ("终端", "★打开后多次重试聚焦", r"function termFocus"),
    ("终端", "★没聚焦时直接敲字也转给终端", r"onTermBtn"),
    # ---- 软件更新 ----
    ("更新", "★设置里可检查 / 一键更新", r"function initUpdate"),
    ("更新", "★检查更新接口", r'"/update/check'),
    ("更新", "★一键更新接口", r'"/update/apply"'),
    ("更新", "★有新版本时横幅提示", r"软件有新版本"),
    ("设置", "★旧设置键自动迁移（改名不丢配置）", r"function migrateLegacyKeys"),
    ("终端", "★终端输出走 SSE 流", r"/pty/\$\{TERM\.id\}/stream"),
    ("终端", "★终端按键上报", r"/pty/\$\{TERM\.id\}/input"),
    ("终端", "★ANSI SGR（颜色/加粗）", r"function termSgr"),
    ("终端", "★ANSI 光标定位 CSI H", r'case "H": case "f"'),
    ("终端", "★只渲染视口附近的行（padding 撑滚动高度）", r"screen\.style\.paddingTop"),
    ("终端", "★渲染节流用 setTimeout（无头不推进 rAF）", r"TERM\.raf = setTimeout"),
    ("终端", "★终端组件缺失给人话", r"面板内终端不可用"),
    ("终端", "★按键映射（方向键/Ctrl+C）", r"function termKey"),
    ("终端", "★开关是「底部上滑抽屉」不是 hidden", r'box\.classList\.add\("open"\)'),
    ("终端", "★打开时给面板让位（html.term-open）", r'classList\.add\("term-open"\)'),
    ("终端", "★抽屉高度可拖动并落盘", r"function termInitResize"),
    ("终端", "★ANSI 色走主题变量（随昼夜切换）", r'"var\(--t0\)"'),
    # ---- 编码模式 ----
    ("编码", "★编码模式开关", r"function codeToggle"),
    ("编码", "★文件树读目录 /fs/list", r"/fs/list\?root="),
    ("编码", "★打开文件 /fs/read", r"/fs/read\?root="),
    ("编码", "★保存写回 /fs/write", r'"/fs/write"'),
    ("编码", "★Ctrl+S 保存", r'key\.toLowerCase\(\) === "s"'),
    ("编码", "★未保存标记（dirty）", r"CODE\.dirty"),
    ("编码", "★在 VS Code 打开这个目录（用当前根目录）", r'openCurrentDir\("editor", CODE\.root\)'),
    ("编码", "★打开时隐藏对话（code-open）", r'classList\.add\("code-open"\)'),
    ("编码", "★编码抽屉左边缘可拖动改宽度", r"function codeInitResize"),
    ("编码", "★打开文件夹（原生选文件夹，换根目录）", r"function codeOpenFolder"),
    ("编码", "★打开文件夹走原生框 /pick/folder", r'api\("/pick/folder", \{ method: "POST" \}\)'),
    ("编码", "★允许代码：在编码抽屉底部嵌入终端", r"function codeTermOn"),
    ("编码", "★嵌入的终端收起后放回 body（PTY 保留）", r"document\.body\.appendChild\(term\)"),
    ("编码", "★合并菜单：打开文件夹 / 新建终端 / VS Code", r'id === "cm-vsc"'),
    ("编码", "★自动保存：输入后防抖写回", r"function codeScheduleSave"),
    ("编码", "★切文件 / 关抽屉前补交自动保存", r"function codeFlushSave"),
    ("编码", "★目录可展开（懒加载子目录）", r"codeLoadDir\(p\)"),
    ("编码", "★Tab 插制表符", r'ed\.dispatchEvent\(new Event\("input"\)\)'),
    ("编码", "★语法高亮（VS Code 配色）", r"function codeHighlightHtml"),
    ("编码", "★高亮 token 规则表", r"HL_RULES"),
    ("编码", "★一键运行：按扩展名挑解释器", r"function codeRunCommand"),
    ("编码", "★一键运行：存盘后把命令送进 run 终端", r"function codeExec"),
    ("编码", "★C/C++ 编译产物名 = 运行路径名（.cocraft-run.exe）",
     r"cocraft-run\.exe && \.\\\\\.cocraft-run\.exe"),
    ("编码", "★C / C++ 语法高亮规则", r"cpp: \["),
    ("编码", "★括号 / 引号自动配对", r"PAIRS\[e\.key\]"),
    ("编码", "★回车自动缩进（承接缩进）", r'if \(e\.key === "Enter"\) \{'),
    ("编码", "★成对删除（Backspace）", r'e\.key === "Backspace" && s === en'),
    ("编码", "★run 终端跟随编码根目录", r"TERM\.embedded && typeof CODE"),
    ("编码", "★按扩展名判语言", r"function codeLangOf"),
    ("编码", "★透明 textarea + 高亮层", r"codeRenderHighlight"),
    ("编码", "★高亮层与编辑区滚动同步", r'addEventListener\("scroll"'),
    ("编码", "★大文件跳过高亮（保流畅）", r"CODE_HL_MAX"),
    ("更新", "★应用内刷新（原生窗口快捷键不一定管用）", r"function safeReload"),
    ("更新", "★点横幅即可刷新", r'bnEl\.addEventListener\("click"'),
    ("更新", "★刷新期间跳过 /bye", r"reloading = true"),
]

# index.html 也要有：龙族标记 / 弹窗 / 控件（这些不是 app.js 里的东西）
HTML_CHECKS = [
    ("龙族", "半朽世界树校徽(SVG symbol)", r'id="mk-tree"'),
    ("龙族", "弹窗标题引用校徽", r'<use href="#mk-tree"'),
    ("龙族", "设置里的歌词翻译开关", r'id="cfg-zh"'),
    ("设置", "设置里的任务栏开关", r'id="cfg-taskbar"'),
    ("设置", "设置里的首次设置按钮", r'id="cfg-setup"'),
    ("设置", "首次设置弹窗", r'id="setup"'),
    ("设置", "新会话弹窗（选工作目录）", r'id="newsess"'),
    ("设置", "新会话目录输入框", r'id="ns-dir"'),
    ("设置", "★右边群聊触发带", r'id="chat-strip"'),
    ("设置", "群聊登录/注册表单", r'id="cc-login"'),
    ("设置", "群聊会话列表", r'id="cc-chats"'),
    ("设置", "★群聊附件按钮", r'id="cc-attach"'),
    ("设置", "★群聊隐藏文件输入", r'id="cc-file"'),
    ("设置", "群聊消息区", r'id="cc-msgs"'),
    ("设置", "群聊发送框", r'id="cc-send"'),
    ("设置", "群聊会话操作菜单（三条横线）", r'id="cc-menu-btn"'),
    ("设置", "群聊邀请成员输入", r'id="cc-invite-ids"'),
    ("设置", "群聊移出成员输入", r'id="cc-remove-id"'),
    ("设置", "★群聊拖拽调宽手柄", r'id="cc-resize"'),
    ("设置", "群聊提示行", r'id="cc-note"'),
    ("设置", "首次设置引擎下拉", r'id="setup-engine"'),
    ("中性化", "agent 编辑弹窗", r'id="agent-edit"'),
    ("中性化", "编辑弹窗里的 provider 输入", r'id="ae-provider"'),
    ("API Key", "设置里的 Key 输入框", r'id="cfg-key-value"'),
    ("模式", "★顶栏模式按钮", r'id="btn-agent"'),
    ("模式", "模式弹窗", r'id="mode-list"'),
    ("模式", "弹窗标题（智能体/模式）", r'id="mode-title"'),
    ("API Key", "向导里的 Key 行", r'id="setup-key-row"'),
    ("API Key", "★变量名改成只读标签（不再两个输入框）", r'id="cfg-key-var"'),
    ("API Key", "向导里的变量名只读标签", r'id="setup-key-var"'),
    ("外观", "头像/素材选择行（data-img）", r'data-img="brand"'),
    ("外观", "空会话主图可换", r'data-img="hero"'),
    ("外观", "空会话贴纸可换", r'data-img="sticker2"'),
    ("外观", "空会话文案可改", r'id="cfg-hero-l1"'),
    ("外观", "空会话署名可改", r'id="cfg-hero-credit"'),
    ("中性化", "provider 自动推断按钮", r'id="ae-guess"'),
    ("中性化", "编辑按钮文案（不再只改命令）", r'编辑当前 agent…'),
    ("设置", "首次设置 agent 下拉", r'id="setup-agent"'),
    ("设置", "首次设置模型下拉", r'id="setup-model"'),
    ("设置", "设置里的左上角名字输入框", r'id="cfg-brand"'),
    ("设置", "设置里的小标签输入框", r'id="cfg-brand-sub"'),
    ("设置", "侧栏小标签元素", r'id="brand-sub"'),
    ("设置", "设置里的两侧音频条开关", r'id="cfg-spec-sides"'),
    ("设置", "两侧音频条高度调节行", r'id="cfg-spec-sides-h"'),
    ("设置", "两侧音频条高度滑块", r'id="cfg-spec-h"'),
    ("设置", "两侧音频条起伏调节行", r'id="cfg-spec-sides-gain"'),
    ("设置", "两侧音频条起伏滑块", r'id="cfg-spec-gain"'),
    ("设置", "会话区左侧音频条", r'id="spec-left"'),
    ("设置", "会话区右侧音频条", r'id="spec-right"'),
    ("设置", "两侧音频条主体外壳", r'id="body-stage"'),
    ("模型", "顶栏模型按钮", r'id="btn-model"'),
    ("模型", "模型选择弹窗", r'id="mdl"'),
    ("壁纸", "已移除分类筛选按钮", r"NOT:wp-fb"),
    ("壁纸", "已移除壁纸音乐按钮", r"NOT:btn-wemusic"),
    ("壁纸", "已移除 scene 筛选按钮", r"NOT:scene-we"),
    ("壁纸", "已移除 we-shot 图层", r"NOT:we-shot"),
    ("壁纸", "设置里动态壁纸目录输入框", r'id="cfg-wall-root"'),
    ("壁纸", "选择壁纸目录按钮", r'id="cfg-wall-root-pick"'),
    ("壁纸", "壁纸目录恢复自动按钮", r'id="cfg-wall-root-auto"'),
    ("音乐", "音乐音频元素", r'id="mus-audio"'),
    ("音乐", "播放条折叠箭头", r'id="p-fold"'),
    ("音乐", "设置里贴Cookie", r'id="cfg-ck-qq"'),
    ("音乐", "播放条平台切换", r'data-p="qq"'),
    ("音乐", "播放条随机按钮", r'id="p-shuffle"'),
    ("音乐", "播放条连播按钮", r'id="p-loop"'),
    ("音乐", "播放条搜索框", r'id="p-q"'),
    ("音乐", "进度条元素", r'id="p-seek"'),
    ("音乐", "已移除音乐条歌单按钮", r"NOT:p-lib"),
    ("引擎", "设置里的引擎下拉", r'id="cfg-engine"'),
    ("引擎", "引擎状态说明文字", r'id="cfg-engine-note"'),
    # ---- 外部打开 / 面板内终端 ----
    ("打开", "★顶栏工具按钮（扳手）", r'id="btn-tools"'),
    ("打开", "★工具菜单容器", r'id="tools-menu"'),
    ("打开", "★工具菜单两项（面板终端 / 编码模式）", r'data-tool="code"'),
    ("编码", "★编码模式面板", r'id="code"'),
    ("编码", "★文件树容器", r'id="code-tree"'),
    ("编码", "★代码编辑框", r'id="code-editor"'),
    ("编码", "★语法高亮层", r'id="code-highlight"'),
    ("编码", "★保存按钮已去掉（改自动保存）", r'NOT:id="code-save"'),
    ("编码", "★合并菜单按钮", r'id="code-menu"'),
    ("编码", "★合并菜单项（打开文件夹 / 新建终端 / VS Code）", r'id="cm-term"'),
    ("编码", "★运行按钮（运行 · Ctrl+Enter）", r'id="code-exec"'),
    ("终端", "★终端面板容器", r'id="term"'),
    ("终端", "★终端可聚焦输入区", r'id="term-wrap"'),
    ("终端", "★终端光标元素", r'id="term-caret"'),
    ("终端", "★终端头按钮（清屏/重开/外部）", r'id="term-restart"'),
    ("终端", "★终端拖高手柄", r'id="term-resize"'),
    # ---- 软件更新 ----
    ("更新", "★设置里「软件更新」行", r'id="upd-check"'),
    ("更新", "★立即更新按钮", r'id="upd-apply"'),
]

# style.css 里的背景层（纯 CSS 的改动 app.js/index.html 都断言不了，这里补上）
CSS_CHECKS = [
    ("壁纸", "展开时视频层也套毛玻璃", r'html\[data-sidebar="open"\] #live-bg'),
    ("壁纸", "有动态层时静态壁纸让位", r"html\.has-live #static-bg \{ display: none; \}"),
    ("壁纸", "静态背景两层交叉淡入", r"#static-bg \.sb\.on"),
    ("壁纸", "静态背景按主题互斥", r'#static-bg \.sb'),
    ("壁纸", "模糊时图层撑出视口(切换不跳)", r"html\.bg-blurred #live-bg \{ inset: -3vmax; \}"),
    ("壁纸", "已删掉冻结帧样式", r"NOT:bg-freeze"),
    ("壁纸", "已删掉 has-freeze 规则", r"NOT:has-freeze"),
    ("壁纸", "已移除 scene 图层样式", r"NOT:lb-we"),
    ("壁纸", "已移除壁纸音乐样式", r"NOT:btn-wemusic"),
    ("音乐", "音频控件样式", r"\.mus-audio"),
    ("音乐", "歌单封面样式", r"\.mus-pl \.pl-cover"),
    ("音乐", "条内歌曲封面样式", r"\.p-results \.it \.it-cover"),
    ("音乐", "主页歌曲封面样式", r"\.mus-song \.s-cover"),
    ("音乐", "★歌词气泡球样式（空闲箭头）", r"\.lyric-ball\.idle"),
    ("音乐", "展开时歌词横向滚动动画", r"@keyframes lyrMarquee"),
    ("壁纸", "目录用等宽字体(反斜杠不显成￥)", r"#cfg-wall-root \{ font-family: var\(--mono\)"),
    ("引擎", "引擎下拉样式", r"#cfg-engine \{"),
    ("主题", "白昼面板也用毛玻璃", r'(?s)\[data-theme="hiru"\] #sidebar.*?backdrop-filter: blur\(10px\)'),
    ("主题", "数学符号字体兜底", r"Cambria Math"),
    ("设置", "★宽行布局（防止 label 被挤成竖排）", r"\.cfg-row\.wide\s*\{"),
    ("设置", "密码框也有样式（不是白框）", r'input\[type="password"\]'),
    ("模式", "★顶栏模式按钮放开 34px 宽度（踩坑 #24）", r"#topbar \.actions #btn-agent"),
    ("消息", "★代码块复制按钮样式", r"\.code-wrap \.copy-code"),
    ("消息", "★消息复制按钮样式", r"\.msg \.who \.copy-btn"),
    ("设置", "★会话项项目名右下角样式", r"\.session \.proj"),
    ("设置", "★群聊触发带样式", r"#chat-strip \{"),
    ("设置", "★群聊抽屉滑入样式", r"\.cocraft\.open"),
    ("设置", "★群聊拖拽手柄样式", r"\.cc-resize"),
    ("设置", "★群聊消息气泡样式", r"\.cc-m \.cc-mb"),
    ("设置", "★群聊文件链接 / 图片预览样式", r"\.cc-mb \.cc-file"),
    ("设置", "★群聊图片放大光标", r"cursor: zoom-in"),
    ("设置", "★群聊会话菜单样式", r"\.cc-menu-pop"),
    ("设置", "★刷新中图标转动样式", r"button\.busy"),
    ("设置", "★群聊分屏：抽屉打开时面板让位", r"html\.cc-open #app \{ padding-right: var\(--cc-w"),
    ("设置", "分屏拖动宽度时不走过渡", r"html\.cc-resizing #app"),
    # ---- 外部打开 / 面板内终端 ----
    ("打开", "★打开菜单样式", r"\.open-menu \{"),
    ("打开", "★顶栏层级（backdrop-filter 会困住菜单）", r"z-index: 15;"),
    ("终端", "★终端抽屉样式", r"\.term \{"),
    ("终端", "★终端光标样式", r"\.term-caret"),
    ("终端", "★终端行高固定（渲染窗口要对齐）", r"line-height: 16px"),
    ("终端", "★终端是底部上滑抽屉（分屏让位）", r"html\.term-open #app \{ padding-bottom"),
    ("终端", "★顶边缘可拖高度", r"\.term-resize \{"),
    ("终端", "★ANSI 调色板按主题分两套", r"--t0: #3b3733"),
    ("终端", "★ANSI 夜间调色板", r"--t0: #000000"),
    # ---- 编码模式 ----
    ("编码", "★编码模式是右侧滑出抽屉（分屏让位）", r"html\.code-open #app \{ padding-right"),
    ("编码", "★编码抽屉左边缘拖动条样式", r"\.code-resize \{"),
    ("编码", "★嵌入式终端（宽度随抽屉、高度可拖）", r"\.term\.embedded \{"),
    ("编码", "★文件树行样式", r"\.code-tree \.tn"),
    ("编码", "★编辑器样式", r"\.code-editor \{"),
    ("编码", "★扳手图标样式", r"\.ico-wrench"),
    ("编码", "★工具菜单里「已开」标记", r"\.open-menu button\.on"),
    ("编码", "★高亮层 / 编辑区层叠对齐", r"\.code-highlight,"),
    ("编码", "★VS Code token 配色（昼 = Light+）", r"--c-comment: #008000"),
    ("编码", "★VS Code token 配色（夜 = Dark+）", r"--c-comment: #6a9955"),
    ("编码", "★运行按钮样式（绯红高亮）", r"#code-exec"),
    ("编码", "★头部控件固定大小（不随拉伸变形）", r"\.code-head > \* \{ flex: 0 0 auto"),
    ("更新", "★可点击的更新横幅", r"\.banner\.clickable"),
]

# ---- ACP 后端（backend/engines/acp/）----
# 以前这个体检只看前端，后端改坏了没有任何网；ACP 那条线尤其需要
# （事件映射 / 记忆 / 导入都是"看不见"的行为）。
# Inno 安装脚本（注释是 `;`，单独扫）
ISS_CHECKS = [
    ("安装包", "★组件 payload 用 DirExists 判断（FileExists 对目录为假！）", r"DirExists\("),
    ("安装包", "音乐/频谱组件声明", r"Name: \"music\""),
    ("安装包", "随包 agent 组件声明（node/codex/claude）", r"Name: \"agent_node\""),
    ("安装包", "Claude 适配器组件", r"Name: \"agent_claude\""),
    ("安装包", "勾了适配器必带 node（Inno 代码守卫）", r"WizardSelectComponents\('agent_node'\)"),
    ("安装包", "per-user 安装（不弹 UAC）", r"PrivilegesRequired=lowest"),
    ("安装包", "卸载清 codex-home（运行时 state）", r'"\{app\}\\agents\\codex\\codex-home"'),
    ("安装包", "卸载先按端口停进程（含安装版端口）", r"17888,17887,17990"),
    ("安装包", "装完跑 init_state", r'init_state\.py"" --app-dir'),
]

PY_CHECKS = [
    ("ACP事件", "★工具输出转字符串（不显示 [object Object]）", r"def normalize_output"),
    ("ACP事件", "工具运行中输出 → session.tool.progress", r"session\.tool\.progress"),
    ("ACP事件", "Codex 增量输出(_meta.terminal_output_delta)", r"def meta_progress"),
    ("ACP事件", "计划 → session.plan.update", r"session\.plan\.update"),
    ("ACP事件", "上下文占用 → session.usage.update", r"session\.usage\.update"),
    ("ACP事件", "上下文压缩摘要进思考", r"compaction_summary_chunk"),
    ("ACP事件", "★每类 update 首次记形状（诊断）", r"_seen_kinds"),
    ("ACP事件", "★每轮收尾记正文计数（诊断）", r"turn done outcome="),
    ("ACP事件", "客户端宣告 terminal_output_delta", r'"terminal_output_delta": True'),
    ("ACP事件", "计划绝不塞进 content（前端只会当原始 JSON）", r'NOT:"type": "plan"'),
    ("ACP权限", "★「始终允许」记忆落盘", r'_acp_always\.json'),
    ("ACP权限", "记住规则的字段", r"def _remember_always"),
    ("ACP权限", "命中规则自动放行", r"def _match_always"),
    ("ACP权限", "自动放行有事件可观测", r'"permission\.auto"'),
    ("ACP权限", "清记忆接口", r"def forget_always"),
    ("ACP会话", "★agent 侧会话列表 session/list", r'"session/list"'),
    ("ACP会话", "导入已有会话", r"def import_remote"),
    ("ACP会话", "★接续前验证能否接回（悬空指针提示）", r'"attach"'),
    ("ACP会话", "★opencode 真导入：只读共享会话库", r"def _opencode_history"),
    ("ACP会话", "接不回时明说（不再静默新建）", r"无法接回"),
    ("ACP会话", "列会话时带对面历史条数", r"def _opencode_message_counts"),
    ("ACP会话", "★接续时用会话自己的 cwd（用错会静默新建）", r"_opencode_session_dir"),
    ("ACP会话", "★打开接续时按 agent 侧自愈目录与历史", r"自愈 %d 处接续会话"),
    ("ACP会话", "空对象宣告(list: {})也算支持", r'"list" in caps'),
    ("ACP会话", "agent 起的真名可自动改名", r"def _auto_title_ok"),
    ("ACP会话", "用户改过的标题不被顶掉", r"def _on_session_info"),
    ("ACP会话", "模式被 agent 改时同步", r"current_mode_update"),
    ("ACP会话", "配置项权威回执", r"config_option_update"),
    ("ACP会话", "★prompt 结果的 usage 累加进 tokens", r"cachedReadTokens"),
    ("ACP会话", "stopReason → 结果", r"max_turn_requests"),
    ("ACP接口", "拉 agent 侧会话的路由", r'"/api/session/remote"'),
    ("ACP接口", "导入路由", r'"/api/session/import"'),
    ("ACP接口", "记忆查询/清除路由", r'"/api/permission/always"'),
    ("ACP接口", "模式清单（与 OpenCode 对齐）", r'"/api/agent"'),
    ("ACP接口", "★扫描本机 agent 路由", r'act == "scan"'),
    ("ACP接口", "扫描本机（deep_scan 发现报告）", r"def deep_scan"),
    ("ACP接口", "★agent stderr 落日志（不再丢）", r"def acp_log"),
    ("ACP接口", "agent 日志查看路由", r'"/engine/acp/log"'),
    ("安装包", "★随包 codex 实跑自检", r"def _check_codex_runtime"),
    ("守护", "★任务栏按窗口判断（残留进程不误藏）", r"def panel_window_state"),
    ("守护", "★原生窗口（WebView2）可选组件", r"def panel_python"),
    ("守护", "★窗口形态设置路由", r'"/panel/window"'),
    ("守护", "★浏览器残留时不重开面板", r"fresh = True\s+#"),
    ("ACP接口", "消息翻页 cursor", r"cursor"),
    ("ACP进程", "★子进程强制 UTF-8（GBK 会把中文变乱码）", r"PYTHONIOENCODING"),
    ("ACP中性", "★provider 可推断（env/命令/config.toml）", r"def guess_provider"),
    ("ACP中性", "空值的 env 不算判断依据", r"if str\(v or \"\"\)\.strip\(\)"),
    ("ACP中性", "读 Codex config.toml 猜 provider", r"_provider_from_codex_home"),
    ("ACP中性", "bootstrap 不预设默认 agent", r'reg = \{"active": "", "agents": agents\}'),
    ("ACP中性", "bootstrap 只挑「真的可用」当 active", r"if status_of\(a, det\)\[\"available\"\]"),
    ("ACP中性", "add_agent 自动补 provider", r'a\["provider"\] = guess_provider\(a\)'),
    ("ACP中性", "autofill 只补空的 provider", r"filledProviders"),
    ("ACP中性", "public 给出 providerGuess 建议", r"providerGuess"),
    ("ACP中性", "Codex 默认项不再塞 OPENAI_API_KEY", r'NOT:"env": \{"OPENAI_API_KEY"'),
    ("ACP中性", "引擎可用性自述 describe()", r"def describe"),
    ("ACP中性", "/engine/status 带上引擎自述", r'"engines": engines\.describe\(\)'),
    ("ACP中性", "编辑弹窗的 provider 推断接口", r'"guess-provider"'),
    ("接口", "★版本号锚定 app.js（别取到 style.css 的 ?v=）", r"app\\\.js\\\?v="),
    ("接口", "★cocraft 代理路由 /cocraft/", r'path\.startswith\("/cocraft/"\)'),
    ("接口", "cocraft 代理可被 env 覆盖（本地调试）", r"OPENCODE_UI_COCRAFT_BASE"),
    # ---- 脱离 OpenCode（面板独立运行）----
    ("脱离OC", "★守护进程按引擎判定是否依赖 OpenCode", r"def opencode_required"),
    ("脱离OC", "★开窗决策抽成纯函数（可单测）", r"def should_open_now"),
    ("脱离OC", "ACP 模式关窗不杀任何东西", r"def should_kill_on_close"),
    ("脱离OC", "ACP 模式不最小化 OpenCode 窗口", r"def should_minimize_opencode"),
    ("脱离OC", "主循环用 should_open_now（不再只看 running）", r"should_open_now\(required, running, fresh, skip_open, closed_at\)"),
    ("脱离OC", "引擎中途可切换（每轮重算 required）", r"required = opencode_required\(\)\s+#"),
    ("脱离OC", "★默认引擎不再写死（第一个可用的）", r"def first_available_engine"),
    ("脱离OC", "没有状态文件时用 first_available_engine", r"return first_available_engine\(\) or DEFAULT_ENGINE"),
    ("脱离OC", "★启动器按引擎决定要不要起 OpenCode", r"def plan"),
    ("脱离OC", "启动器 acp 模式跳过自愈", r'"heal": not panel_only'),
    # ---- 子命令式 ACP（OpenCode 自带 `acp` 子命令）----
    ("子命令ACP", "★识别「CLI 的 acp 子命令」这种形态", r"def find_subcommand_acp"),
    ("子命令ACP", "已登记的规格含 opencode-cli", r'"opencode-cli\.exe"'),
    ("子命令ACP", "★子命令式改名「OpenCode 客户端」", r"OpenCode 客户端"),
    ("子命令ACP", "★扫描时按真实路径去重（junction 不会扫出两条）", r"os\.path\.realpath\(p\)"),
    ("子命令ACP", "push 用真实路径做去重键", r"norm\.append\(os\.path\.realpath\(sx\)\.lower\(\)\)"),
    ("子命令ACP", "选文件夹也能认出子命令式", r"hit = find_subcommand_acp\(\[d\]\)"),
    ("子命令ACP", "候选复用规格里的名字", r"_spec_for_command\(cmd\)"),
    ("子命令ACP", "扫到候选里也推送子命令式", r'push\(spec\["label"\], cmd,'),
    ("子命令ACP", "★基线 mode 该 agent 没有就跳过（不报 -32602）", r"这个 agent 没有（可用："),
    ("子命令ACP", "★每个 agent 自己的 mode 覆盖共享基线", r'b2\["mode"\] = a\["mode"\]'),
    ("子命令ACP", "改模型以 agent 回执为准（不许盲信）", r"没被 agent 接受"),
    ("子命令ACP", "public 回 mode 字段", r'"mode": str\(a\.get\("mode"\) or ""\)'),
    ("子命令ACP", "patch 白名单含 mode", r'"provider", "mode"'),
    # ---- ACP 对话（图片 / 损坏历史自愈，2026-10-01）----
    ("ACP对话", "★图片发 ACP image 块（不再只发 resource_link）", r'"type": "image", "mimeType"'),
    ("ACP对话", "★读 promptCapabilities 决定图片/内嵌资源", r"def _prompt_caps"),
    ("ACP对话", "★data URL 解析", r"def _data_url_parts"),
    ("ACP对话", "★附件落库补 mime/data（刷新后缩略图不丢）", r"def _norm_attachment"),
    ("ACP对话", "★识别悬空 tool_call 的 provider 报错", r"def _is_dangling_tool_error"),
    ("ACP对话", "★命中后丢弃 agent 绑定（自愈）", r"def _drop_agent_binding"),
    ("ACP对话", "★_forceNew 跳过 resume（坏会话不接回）", r's\.pop\("_forceNew"'),
    # ---- agent 侧 id → 本地 id 别名表（修「正文全丢/空回复」，2026-10-01）----
    ("ACP对话", "★agent id → 本地 id 别名表", r"self\._alias = \{\}"),
    ("ACP对话", "★_local_sid 解析函数", r"def _local_sid"),
    ("ACP对话", "★通知入口先解析本地 id", r'sid = self\._local_sid\(params\.get\("sessionId"\)\)'),
    ("ACP对话", "★_load 重建别名", r'self\._alias\[a\] = str\(s\.get\("id"\)\)'),
    ("ACP对话", "★session_new 降级也登记别名", r"self\._alias\[str\(new_sid\)\] = str\(sid\)"),
    # ---- 重置后把本地历史「补记」给 agent（ACP 没有灌历史接口）----
    ("ACP对话", "★补记文本生成器（带条数/字符上限）", r"def _reseed_text"),
    ("ACP对话", "★补记块拼在用户消息之前（同一轮）", r'"text": note'),
    # ---- 默认模式跟随用户最后一次选择（2026-10-01）----
    ("ACP对话", "★模式偏好落盘", r"def remember_mode"),
    ("ACP对话", "★_apply_baseline 优先用模式偏好", r"pref = str\(load_mode_pref\(\)"),
    ("ACP对话", "★切模式时记住这次选择", r"remember_mode\(self\.agent_id, aid\)"),
    ("ACP对话", "★_load 把本地 id 归一成 agent id（两引擎同一条）", r's\["id"\] = _a'),
    ("ACP对话", "★三处 _needsReseed 触发点", r'\["_needsReseed"\] = True'),
    # ---- 可选组件（安装包：音乐服务 / 音频频谱）----
    ("可选组件", "★按组件找解释器（venv 或 site-packages）", r"def _component_python"),
    ("可选组件", "安装包形态：自带解释器 + PYTHONPATH", r"def _component_env"),
    ("可选组件", "音乐服务没装就静默跳过", r"if not MUSIC_SVC_PY:"),
    ("可选组件", "频谱没装就静默跳过", r"if not AUDIO_PY:"),
    ("可选组件", "★缺音乐服务时给人话（503 + reason）", r'"error": music_component\(\)\["reason"\]'),
    ("可选组件", "组件自述接口 /music/component", r'"/music/component"'),
    # ---- 安装包（packaging/）----
    # ---- 安装包（packaging/ + tools/selftest.py，见 PY 扫描列表）----
    ("安装包", "★payload 收集（核心/组件/agent）", r"def stage_agent"),
    ("安装包", "可选组件按 site-packages 打包", r"def stage_components"),
    ("安装包", "★安装时修 ._pth（嵌入式解释器隔离模式）", r"def fix_pth"),
    ("安装包", "定位用户目录不依赖 LOCALAPPDATA", r"def env_path"),
    ("安装包", "★组件目录也写进 ._pth（._pth 会忽略 PYTHONPATH）", r'\.\.\\\\runtime\\\\site-packages'),
    ("安装包", "★安装版端口与开发版隔离（_panel.json）", r"def read_ports"),
    ("安装包", "watch 支持 --port/--lock-port", r"--lock-port"),
    ("安装包", "ensure_server 把端口传给 server.py", r'"--music-port", str\(MUSIC_PORT\)'),
    ("安装包", "server.py 支持 --music-port", r'"--music-port"'),
    # ---- Claude Code（与 codex 同构）----
    ("Claude", "★与 codex 同构的两个内置档案", r"def _claude_defaults"),
    ("Claude", "claude-node（node 适配器）", r'"claude-node"'),
    ("Claude", "claude-client（本机客户端）", r'"claude-client"'),
    ("Claude", "★检测 claude / claude-code-acp / 本地适配器", r'"claudeAdapter"'),
    ("Claude", "适配器入口查找（通用 _adapter_entry）", r"def _adapter_entry"),
    ("Claude", "★依赖判定：无登录态时提示（适配器自带 CLI，不误报缺 CLI）", r"Claude Code 登录（或 ANTHROPIC_API_KEY）"),
    ("Claude", "claude-client 才要求 CLI/适配器", r"claude-code-acp / Claude Code CLI"),
    ("Claude", "登录态探测（~/.claude 或 ANTHROPIC_API_KEY）", r"def _has_claude_auth"),
    ("Claude", "★包内 agents 目录也算探测位置（安装版状态才正确）", r'os\.path\.join\(ROOT_DIR, "agents", "node"'),
    ("Claude", "★provider 关键词整词命中（路径名不误导）", r"def _kw_hit"),
    ("Claude", "命令只看文件名（绝对路径的目录名不算线索）", r"os\.path\.basename\(sx\)"),
    ("安装包", "★save_registry 留一份 .bak（误写可捞）", r'AGENTS_FILE \+ "\.bak"'),
    ("安装包", "★autofill 支持 save=False（探针别写盘）", r"def autofill\(reg: dict = None, save: bool = True\)"),
    ("Claude", "autofill 把 npx 升级成本地适配器", r'"@zed-industries/claude-code-acp"'),
    ("Claude", "候选扫描含 Claude Code 两类", r"Claude Code · 本机客户端"),
    ("Claude", "★便携 node 定点查找（大目录会吃光 _walk_find 上限）", r"def _glob_node_exe"),
    ("Claude", "按要求不探测 VS Code 缓存", r"NOT:agent-host"),
    ("Claude", "provider 由推断而来（claude → anthropic 线索）", r'"claude", "ANTHROPIC_API_KEY"'),
    ("安装包", "★初始化不写任何密钥", r"API Key 不随包"),
    ("安装包", "随包 agent 用 app 相对路径", r'"agents", "node", "node\.exe"'),
    ("安装包", "自检脚本（装完能跑）", r"cocraft 自检"),
    ("安装包", "自检也检查 Claude 适配器 + 登录态", r"Claude 登录态"),
    ("安装包", "★自检把「ACP server 超时」当正常（它会等 stdin）", r"except subprocess\.TimeoutExpired"),
    # ---- 模型 API Key（装完怎么填）----
    ("API Key", "★基线环境变量写入（密钥只落本机）", r"def update_baseline_env"),
    ("API Key", "★回给界面的只有掩码", r"def mask_secret"),
    ("API Key", "改 Key 后重启 ACP 子进程", r"def set_baseline_env"),
    ("API Key", "基线视图（掩码 + 变量名）", r"def baseline_view"),
    ("API Key", "接口 /engine/acp/baseline", r'"/engine/acp/baseline"'),
    # ---- 自定义外观（头像 / 空会话素材）----
    ("外观", "★素材状态文件（只记本机路径）", r"APPEARANCE_FILE"),
    ("外观", "允许的图片扩展名白名单", r"IMAGE_EXTS"),
    ("外观", "★接口 /appearance（读/写/清除）", r'path == "/appearance"'),
    ("外观", "素材走 /appearance/img 代理（file:// 会被浏览器拦）", r'path == "/appearance/img"'),
    ("外观", "原生选图框脚本", r"pick_image\.ps1"),
    ("外观", "选图走共用 _pick_path（BOM 要剥掉）", r'lstrip\("\\ufeff"\)'),
    # ---- 引擎：opencode 回归（安装版曾把 opencode 判成未就绪）----
    ("引擎", "★引擎=opencode 但没跑 → 拉起桌面端", r"def launch_desktop"),
    ("引擎", "★切到 opencode 时拉起", r"已拉起 OpenCode 桌面端"),
    ("引擎", "★多候选找 service.json（缺 USERPROFILE 也能找到）", r"def service_states"),
    ("引擎", "用户目录多线索推导", r"def _home_dirs"),
    ("引擎", "★装了 CLI 也算可用（不把用户挡在门外）", r"def cli_path"),
    ("引擎", "NOT:写死 expanduser 当唯一来源",
     r"NOT:SERVICE_STATE = os\.path\.join\(os\.path\.expanduser"),
    ("引擎", "★自愈：注册表缺 opencode-acp 就自动补", r"def ensure_opencode_agent"),
    ("引擎", "★server.py 每次启动都调一次自愈", r"acp_agents\.ensure_opencode_agent\(\)"),
    ("引擎", "★随包 OpenCode（node 版）查找器", r"def find_bundled_opencode"),
    ("引擎", "★随包 OpenCode 自愈（与客户端分开）", r"def ensure_bundled_opencode_agent"),
    ("引擎", "★server.py 启动时也补随包 OpenCode", r"acp_agents\.ensure_bundled_opencode_agent\(\)"),
    ("引擎", "★随包 OpenCode id = opencode-node", r'"id": "opencode-node"'),
    ("引擎", "★客户端探测跳过随包目录（互不抢占）", r"skip_roots=\[BUNDLED_OPENCODE_DIR\]"),
    ("引擎", "自愈加进来的 agent 标成内置（不给删）", r'"builtin": True'),
    ("安装包", "★init_state 用后端探测器找 opencode-acp", r"ag\.find_subcommand_acp\(\)"),
    ("安装包", "★init_state 登记随包 OpenCode（node 版）", r"ag\.find_bundled_opencode\(\)"),
    ("安装包", "★随包目录单独识别（与客户端分开）", r"def _is_bundled_opencode_path"),
    # ---- 外部打开目录 ----
    ("外部打开", "★统一入口 open_in（terminal/editor/explorer）", r"def open_in"),
    ("外部打开", "★.cmd/.bat 走 cmd /c（CreateProcess 跑不了批处理）", r'endswith\(\("\.cmd", "\.bat"\)\)'),
    ("外部打开", "★终端显式指定 shell（不吃 WT 默认 profile）", r"argv\.append\(sh\)"),
    ("外部打开", "★优先 PowerShell 7（pwsh）再退回 5.1", r"def find_pwsh"),
    ("外部打开", "★VS Code 优先真 exe（code.cmd → Code.exe）", r"def _cmd_to_exe"),
    ("外部打开", "★打开目录路由 /open/dir", r'"/open/dir"'),
    # ---- 面板内终端（ConPTY，可选组件）----
    ("终端", "★终端走可选组件（venv / site-packages）", r"def terminal_python"),
    ("终端", "★宿主协议：JSON 行（out/exit）", r'"t": "out"'),
    ("终端", "★终端组件自述接口 /pty/component", r'"/pty/component"'),
    ("终端", "★终端 SSE 流分支", r'action == "stream"'),
    ("终端", "★会话数上限（防泄漏）", r"_MAX_SESSIONS"),
    ("终端", "★孤儿终端宿主纳入清理", r"pty_host"),
    # ---- 软件更新 ----
    ("更新", "★读本地版本（VERSION）", r"def current_version"),
    ("更新", "★查 Latest Release", r"def check"),
    ("更新", "★版本比较（SemVer 主.次.修订）", r"def _verkey"),
    ("更新", "★挑安装包资产", r"def _pick_asset"),
    ("更新", "★一键更新：下载 + 静默装 + 自动重启", r"def apply_update"),
    ("更新", "★脱离本进程执行（安装器会杀我们）", r"DETACHED_PROCESS"),
    ("更新", "★不信任客户端 URL（自己重查）", r"check\(force=True\)"),
    ("更新", "★路由 /update/check", r'"/update/check"'),
    ("更新", "★路由 /update/apply", r'"/update/apply"'),
    ("更新", "★仓库已改名 cocraft", r"huaian307/cocraft"),
    ("更新", "★安装包名前缀 cocraft-setup-（兼容旧前缀）", r'ASSET_PREFIXES = \("cocraft-setup-"'),
    # ---- 安装版启动（嵌入式 Python ._pth 隔离） ----
    ("安装包", "★本地模块前置 sys.path（否则 import pty 会命中标准库 Unix pty）", r"sys\.path\.remove\(HERE\)"),
    ("安装包", "NOT:不再用「不在才插入」的 sys.path 写法", r"NOT:not in sys\.path"),
    ("安装包", "★._pth 收录所有组件目录（不写死 music/audio）", r"os\.listdir\(comp_root\)"),
    ("安装包", "★启动清理放后台线程（powershell 坏了也不拖垮面板）", r"_cleanup_stale_bg"),
    ("安装包", "★没装 QQ音乐就不起 SMTC（少起 powershell）", r"def _qqmusic_installed"),
    ("守护", "★powershell 起不来就停用（0xc0000142 不再弹框）", r"_ps_state\[.broken.\]"),
    # ---- 进程查询 / 关机弹框（2026-10-01）----
    ("守护", "★进程枚举纯 ctypes（不再起 tasklist）", r"def pids_named"),
    ("守护", "★存活检查纯 ctypes（不起 tasklist）", r"def pid_alive"),
    ("守护", "★守护里 OpenCode 检测走 is_running", r"_proc\.is_running\(\"OpenCode\.exe\"\)"),
    ("守护", "★error mode 抑制「应用程序无法正常启动」硬错误框", r"def set_error_mode"),
    ("守护", "★关窗联动：只看句柄/采纳 PID，查不到=没开（老行为）", r"return \(bool\(found\), found\)"),
    ("守护", "★刚重启面板服务后的静默期不做联动（防误杀 OpenCode）", r"RESTART_QUIET"),
    ("守护", "★守护兜底拉起 OpenCode（引擎=opencode 没跑时，30s 节流）", r"last_launch_try"),
    ("守护", "★原生窗口加载看门狗（白屏 → 换浏览器窗口）", r"NATIVE_LOAD_TIMEOUT"),
    ("守护", "★面板窗口禁用第三方扩展（避免连带拉起 XDown 之类）", r"--disable-extensions"),
    ("守护", "★服务/启动器也调 set_error_mode", r"set_error_mode\(\)"),
    ("守护", "★自愈/终端宿主内联抑制硬错误框", r"kernel32\.SetErrorMode"),
    # ---- 编码模式（引擎无关的文件读写） ----
    ("编码", "★列目录", r"def list_dir"),
    ("编码", "★读文件", r"def read_file"),
    ("编码", "★写文件", r"def write_file"),
    ("编码", "★越界校验（realpath 前缀）", r"not t\.startswith\(r \+ os\.sep\)"),
    ("编码", "★跳过重目录（node_modules 等）", r"SKIP_DIRS"),
    ("编码", "★路由 /fs/list", r'"/fs/list"'),
    ("编码", "★路由 /fs/read", r'"/fs/read"'),
    ("编码", "★路由 /fs/write", r'"/fs/write"'),
]



def _hit(pattern: str, text: str) -> bool:
    """以 `NOT:` 开头 = 必须**不存在**（用来断言"旧的实现确实删干净了"）。"""
    if pattern.startswith("NOT:"):
        return re.search(pattern[4:], text) is None
    return re.search(pattern, text) is not None


def main() -> int:
    app = io.open(os.path.join(HERE, "frontend", "app.js"), encoding="utf-8").read()
    # 去掉注释，避免"注释里写了但代码没了"的假通过
    js = re.sub(r"/\*.*?\*/", " ", app, flags=re.S)
    js = re.sub(r"(?<!:)//[^\n]*", " ", js)
    html = io.open(os.path.join(HERE, "frontend", "index.html"), encoding="utf-8").read()
    css = re.sub(r"/\*.*?\*/", " ",
                 io.open(os.path.join(HERE, "frontend", "style.css"), encoding="utf-8").read(), flags=re.S)

    # ACP 后端也纳入体检（以前只看前端，后端改坏了没有任何网）
    py = []
    py_files = [os.path.join("backend", "engines", "acp", n)
                for n in ("map_events.py", "service.py", "engine.py", "process.py",
                          "client.py", "agents.py")]
    py_files += [os.path.join("backend", "engines", "__init__.py"),
                 os.path.join("backend", "engines", "opencode.py"),
                 os.path.join("backend", "server.py"),
                 os.path.join("backend", "watch.py"),
                 os.path.join("backend", "panel_port.py"),
                 os.path.join("backend", "cleanup.py"),
                 os.path.join("backend", "external.py"),
                 os.path.join("backend", "fsview.py"),
                 os.path.join("backend", "updater.py"),
                 os.path.join("backend", "procutils.py"),
                 os.path.join("backend", "pty.py"),
                 os.path.join("backend", "pty_host.py"),
                 os.path.join("launchers", "launch_opencode.py"),
                 os.path.join("scripts", "heal_opencode_link.py"),
                 os.path.join("packaging", "build.py"),
                 os.path.join("packaging", "init_state.py"),
                 os.path.join("tools", "selftest.py")]
    for rel in py_files:
        p = os.path.join(HERE, rel)
        src = io.open(p, encoding="utf-8").read()
        src = re.sub(r'"""(?:.|\n)*?"""', " ", src)       # 去掉文档字符串
        src = re.sub(r"(?m)^\s*#.*$", " ", src)           # 去掉整行注释
        py.append("/* %s */\n%s" % (rel.replace("\\", "/"), src))
    py = "\n".join(py)
    # Inno 脚本单独扫（它的注释是 `;`，用 # 会误删 #define 行）
    iss = io.open(os.path.join(HERE, "packaging", "cocraft.iss"), encoding="utf-8").read()
    iss = re.sub(r"(?m)^\s*;.*$", " ", iss)

    fails: list = []
    total = 0
    for suffix, checks, text in (("", CHECKS, js),
                                (" · index.html", HTML_CHECKS, html),
                                (" · style.css", CSS_CHECKS, css),
                                 (" · acp", PY_CHECKS, py),
                                 (" · iss", ISS_CHECKS, iss)):
        group = None
        for g, name, pattern in checks:
            if g != group:
                print(f"\n[{g}{suffix}]")
                group = g
            total += 1
            ok = _hit(pattern, text)
            print(f"  {'OK  ' if ok else 'MISS'} {name}")
            if not ok:
                fails.append(f"{g}/{name}")

    print(f"\n共 {total} 项，缺失 {len(fails)} 项")
    if fails:
        print("缺失清单：")
        for f in fails:
            print("   -", f)
        return 1
    print("result: PASS")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
